import { BobBlueprint, Entity, Field } from "./mermaidGenerator";

/**
 * Maps field types to example values for API documentation
 */
function getExampleValue(type: string): any {
  const normalized = type.toLowerCase().trim();
  
  if (normalized.includes("string") || normalized.includes("text")) return "string";
  if (normalized.includes("int") || normalized.includes("integer")) return 0;
  if (normalized.includes("decimal") || normalized.includes("float")) return 0.0;
  if (normalized.includes("date") && !normalized.includes("time")) return "2024-01-01";
  if (normalized.includes("datetime") || normalized.includes("timestamp")) return "2024-01-01T00:00:00Z";
  if (normalized.includes("bool") || normalized.includes("boolean")) return false;
  
  return "string"; // fallback
}

/**
 * Generates a JSON body example for POST/PUT requests based on entity fields
 */
function generateRequestBody(entity: Entity, excludePrimaryKey: boolean = true): string {
  const bodyObj: Record<string, any> = {};
  
  entity.fields.forEach((field: Field) => {
    // Skip primary keys for POST requests (usually auto-generated)
    if (excludePrimaryKey && field.primary_key) {
      return;
    }
    
    bodyObj[field.name] = getExampleValue(field.type);
  });
  
  return JSON.stringify(bodyObj, null, 2);
}

/**
 * Generates the entity name in plural form for REST conventions
 */
function pluralize(entityName: string): string {
  const lower = entityName.toLowerCase();
  
  // Simple pluralization rules
  if (lower.endsWith('y')) {
    return lower.slice(0, -1) + 'ies';
  }
  if (lower.endsWith('s') || lower.endsWith('x') || lower.endsWith('ch') || lower.endsWith('sh')) {
    return lower + 'es';
  }
  
  return lower + 's';
}

/**
 * Transforms the IBM Bob JSON Blueprint into a Markdown API Contract document
 * with standard RESTful endpoints for each entity.
 */
export function generateApiContract(blueprint: any): string {
  const typedBlueprint = blueprint as BobBlueprint;
  
  if (!typedBlueprint || !typedBlueprint.entities || typedBlueprint.entities.length === 0) {
    return "# API Contract\n\nNo entities found to generate API endpoints.";
  }

  let markdown = "# API Contract Documentation\n\n";
  markdown += "_Generated by BobArchitecLegacyLens_\n\n";
  markdown += "This document describes the RESTful API endpoints for the system entities.\n\n";
  markdown += "---\n\n";

  typedBlueprint.entities.forEach((entity: Entity) => {
    const entityNamePlural = pluralize(entity.name);
    const basePath = `/api/${entityNamePlural}`;
    
    markdown += `## ${entity.name}\n\n`;
    markdown += `**Base Path:** \`${basePath}\`\n\n`;
    markdown += `**Table:** \`${entity.table}\`\n\n`;
    
    // GET All
    markdown += `### GET ${basePath}\n\n`;
    markdown += `**Description:** Retrieve all ${entityNamePlural}\n\n`;
    markdown += `**Response:** \`200 OK\`\n\n`;
    markdown += "```json\n";
    markdown += "[\n";
    markdown += "  {\n";
    entity.fields.forEach((field: Field, index: number) => {
      const comma = index < entity.fields.length - 1 ? "," : "";
      markdown += `    "${field.name}": ${JSON.stringify(getExampleValue(field.type))}${comma}\n`;
    });
    markdown += "  }\n";
    markdown += "]\n";
    markdown += "```\n\n";
    
    // GET by ID
    const primaryKeyField = entity.fields.find(f => f.primary_key);
    const idParam = primaryKeyField ? primaryKeyField.name : "id";
    
    markdown += `### GET ${basePath}/{${idParam}}\n\n`;
    markdown += `**Description:** Retrieve a single ${entity.name} by ${idParam}\n\n`;
    markdown += `**Parameters:**\n`;
    markdown += `- \`${idParam}\` (path parameter): The unique identifier\n\n`;
    markdown += `**Response:** \`200 OK\`\n\n`;
    markdown += "```json\n";
    markdown += "{\n";
    entity.fields.forEach((field: Field, index: number) => {
      const comma = index < entity.fields.length - 1 ? "," : "";
      markdown += `  "${field.name}": ${JSON.stringify(getExampleValue(field.type))}${comma}\n`;
    });
    markdown += "}\n";
    markdown += "```\n\n";
    
    // POST
    markdown += `### POST ${basePath}\n\n`;
    markdown += `**Description:** Create a new ${entity.name}\n\n`;
    markdown += `**Request Body:**\n\n`;
    markdown += "```json\n";
    markdown += generateRequestBody(entity, true);
    markdown += "\n```\n\n";
    markdown += `**Response:** \`201 Created\`\n\n`;
    markdown += "```json\n";
    markdown += "{\n";
    entity.fields.forEach((field: Field, index: number) => {
      const comma = index < entity.fields.length - 1 ? "," : "";
      markdown += `  "${field.name}": ${JSON.stringify(getExampleValue(field.type))}${comma}\n`;
    });
    markdown += "}\n";
    markdown += "```\n\n";
    
    // PUT
    markdown += `### PUT ${basePath}/{${idParam}}\n\n`;
    markdown += `**Description:** Update an existing ${entity.name}\n\n`;
    markdown += `**Parameters:**\n`;
    markdown += `- \`${idParam}\` (path parameter): The unique identifier\n\n`;
    markdown += `**Request Body:**\n\n`;
    markdown += "```json\n";
    markdown += generateRequestBody(entity, false);
    markdown += "\n```\n\n";
    markdown += `**Response:** \`200 OK\`\n\n`;
    markdown += "```json\n";
    markdown += "{\n";
    entity.fields.forEach((field: Field, index: number) => {
      const comma = index < entity.fields.length - 1 ? "," : "";
      markdown += `  "${field.name}": ${JSON.stringify(getExampleValue(field.type))}${comma}\n`;
    });
    markdown += "}\n";
    markdown += "```\n\n";
    
    // DELETE
    markdown += `### DELETE ${basePath}/{${idParam}}\n\n`;
    markdown += `**Description:** Delete a ${entity.name}\n\n`;
    markdown += `**Parameters:**\n`;
    markdown += `- \`${idParam}\` (path parameter): The unique identifier\n\n`;
    markdown += `**Response:** \`204 No Content\`\n\n`;
    
    markdown += "---\n\n";
  });

  markdown += "## Common Response Codes\n\n";
  markdown += "- `200 OK`: Request successful\n";
  markdown += "- `201 Created`: Resource created successfully\n";
  markdown += "- `204 No Content`: Resource deleted successfully\n";
  markdown += "- `400 Bad Request`: Invalid request data\n";
  markdown += "- `404 Not Found`: Resource not found\n";
  markdown += "- `500 Internal Server Error`: Server error\n\n";

  return markdown;
}

// Made with Bob
