import { BobBlueprint, Entity, Field } from "./mermaidGenerator";

/**
 * Maps generic JSON types from IBM Bob to PostgreSQL data types.
 */
function mapTypeToPostgres(type: string): string {
  const normalized = type.toLowerCase().trim();
  
  if (normalized.includes("string") || normalized.includes("text")) return "VARCHAR(255)";
  if (normalized.includes("int") || normalized.includes("integer")) return "INTEGER";
  if (normalized.includes("decimal") || normalized.includes("float")) return "DECIMAL(10, 2)";
  if (normalized.includes("date") && !normalized.includes("time")) return "DATE";
  if (normalized.includes("datetime") || normalized.includes("timestamp")) return "TIMESTAMP";
  if (normalized.includes("bool") || normalized.includes("boolean")) return "BOOLEAN";
  
  return "VARCHAR(255)"; // fallback
}

/**
 * Transforms the IBM Bob JSON Blueprint into PostgreSQL CREATE TABLE statements.
 */
export function generateSqlSchema(blueprint: BobBlueprint): string {
  if (!blueprint || !blueprint.entities) return "-- No entities found to generate SQL.";

  let sqlStr = "-- Generated by BobArchitecLegacyLens\n";
  sqlStr += "-- Target Database: PostgreSQL\n\n";

  blueprint.entities.forEach((entity: Entity) => {
    sqlStr += `CREATE TABLE ${entity.table} (\n`;
    
    const fieldLines: string[] = [];
    
    entity.fields.forEach((field: Field) => {
      let line = `    ${field.name} ${mapTypeToPostgres(field.type)}`;
      
      if (field.primary_key) {
        if (field.auto_increment) {
          // Replace INTEGER with SERIAL for PKs in Postgres
          line = line.replace("INTEGER", "SERIAL");
        }
        line += " PRIMARY KEY";
      }
      
      // We assume fields are nullable unless specified. 
      // If the JSON explicitly says nullable: false, we add NOT NULL.
      // (Handling this depends on exactly how Bob formats the JSON, but usually we look for a 'nullable' property)
      const fieldAsAny = field as any;
      if (fieldAsAny.nullable === false) {
        line += " NOT NULL";
      }

      if (fieldAsAny.unique) {
        line += " UNIQUE";
      }

      fieldLines.push(line);
    });

    // Handle Foreign Keys natively if provided in the JSON
    entity.fields.forEach((field: Field) => {
      if (field.foreign_key) {
        const [refTable, refColumn] = field.foreign_key.split(".");
        if (refTable && refColumn) {
           fieldLines.push(`    FOREIGN KEY (${field.name}) REFERENCES ${refTable}(${refColumn}) ON DELETE CASCADE`);
        }
      }
    });

    sqlStr += fieldLines.join(",\n");
    sqlStr += "\n);\n\n";
  });

  return sqlStr;
}
