/**
 * SQL Schema Generator
 * 
 * Transforms IBM Bob's blueprint into PostgreSQL CREATE TABLE statements.
 */

import { 
  BobBlueprint, 
  Entity, 
  Field, 
  validateBlueprint, 
  sanitizeSqlIdentifier 
} from '@/types/blueprint';

/**
 * Maps generic JSON types from IBM Bob to PostgreSQL data types.
 * @param type - The generic type string from the blueprint
 * @returns PostgreSQL data type
 */
function mapTypeToPostgres(type: string): string {
  const normalized = type.toLowerCase().trim();
  
  if (normalized.includes("string") || normalized.includes("text")) return "VARCHAR(255)";
  if (normalized.includes("int") || normalized.includes("integer")) return "INTEGER";
  if (normalized.includes("decimal") || normalized.includes("float")) return "DECIMAL(10, 2)";
  if (normalized.includes("date") && !normalized.includes("time")) return "DATE";
  if (normalized.includes("datetime") || normalized.includes("timestamp")) return "TIMESTAMP";
  if (normalized.includes("bool") || normalized.includes("boolean")) return "BOOLEAN";
  
  return "VARCHAR(255)"; // fallback
}

/**
 * Transforms the IBM Bob JSON Blueprint into PostgreSQL CREATE TABLE statements.
 * @param blueprint - The analyzed blueprint from IBM Bob
 * @returns PostgreSQL SQL schema as a string
 * @throws {Error} If blueprint is invalid or contains unsafe identifiers
 */
export function generateSqlSchema(blueprint: BobBlueprint): string {
  // Validate the blueprint structure and identifiers
  validateBlueprint(blueprint);

  let sqlStr = "-- Generated by BobArchitecLegacyLens\n";
  sqlStr += "-- Target Database: PostgreSQL\n\n";

  blueprint.entities.forEach((entity: Entity) => {
    // Sanitize table name (already validated in validateBlueprint, but double-check)
    const tableName = sanitizeSqlIdentifier(entity.table, `table name for entity "${entity.name}"`);
    
    sqlStr += `CREATE TABLE ${tableName} (\n`;
    
    const fieldLines: string[] = [];
    
    entity.fields.forEach((field: Field) => {
      // Sanitize field name
      const fieldName = sanitizeSqlIdentifier(field.name, `field name in table "${tableName}"`);
      
      let line = `    ${fieldName} ${mapTypeToPostgres(field.type)}`;
      
      if (field.primary_key) {
        if (field.auto_increment) {
          // Replace INTEGER with SERIAL for auto-incrementing PKs in Postgres
          line = line.replace("INTEGER", "SERIAL");
        }
        line += " PRIMARY KEY";
      }
      
      // Handle nullable constraint using type guard
      if ('nullable' in field && field.nullable === false) {
        line += " NOT NULL";
      }

      // Handle unique constraint using type guard
      if ('unique' in field && field.unique === true) {
        line += " UNIQUE";
      }

      fieldLines.push(line);
    });

    // Handle Foreign Keys natively if provided in the JSON
    entity.fields.forEach((field: Field) => {
      if (field.foreign_key) {
        const parts = field.foreign_key.split(".");
        if (parts.length === 2) {
          const [refTable, refColumn] = parts;
          
          // Sanitize foreign key references
          const sanitizedRefTable = sanitizeSqlIdentifier(refTable, "foreign key reference table");
          const sanitizedRefColumn = sanitizeSqlIdentifier(refColumn, "foreign key reference column");
          const sanitizedFieldName = sanitizeSqlIdentifier(field.name, "foreign key field");
          
          fieldLines.push(
            `    FOREIGN KEY (${sanitizedFieldName}) REFERENCES ${sanitizedRefTable}(${sanitizedRefColumn}) ON DELETE CASCADE`
          );
        } else {
          console.warn(
            `Invalid foreign key format for field "${field.name}" in table "${tableName}": ` +
            `expected "table.column", got "${field.foreign_key}"`
          );
        }
      }
    });

    sqlStr += fieldLines.join(",\n");
    sqlStr += "\n);\n\n";
  });

  return sqlStr;
}

// Made with Bob
